/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as EcosistemaRouteImport } from './routes/ecosistema'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as AziendaRouteImport } from './routes/azienda'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemaRoute = EcosistemaRouteImport.update({
  id: '/ecosistema',
  path: '/ecosistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const AziendaRoute = AziendaRouteImport.update({
  id: '/azienda',
  path: '/azienda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/azienda': typeof AziendaRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema': typeof EcosistemaRoute
  '/prezzi': typeof PrezziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/azienda': typeof AziendaRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema': typeof EcosistemaRoute
  '/prezzi': typeof PrezziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/azienda': typeof AziendaRoute
  '/contatti': typeof ContattiRoute
  '/ecosistema': typeof EcosistemaRoute
  '/prezzi': typeof PrezziRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/azienda'
    | '/contatti'
    | '/ecosistema'
    | '/prezzi'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/azienda'
    | '/contatti'
    | '/ecosistema'
    | '/prezzi'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/azienda'
    | '/contatti'
    | '/ecosistema'
    | '/prezzi'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AziendaRoute: typeof AziendaRoute
  ContattiRoute: typeof ContattiRoute
  EcosistemaRoute: typeof EcosistemaRoute
  PrezziRoute: typeof PrezziRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistema': {
      id: '/ecosistema'
      path: '/ecosistema'
      fullPath: '/ecosistema'
      preLoaderRoute: typeof EcosistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azienda': {
      id: '/azienda'
      path: '/azienda'
      fullPath: '/azienda'
      preLoaderRoute: typeof AziendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AziendaRoute: AziendaRoute,
  ContattiRoute: ContattiRoute,
  EcosistemaRoute: EcosistemaRoute,
  PrezziRoute: PrezziRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
